### ISSUE TITLE
Implement Cross Site Scripting (XSS) Security to the Server App

### ISSUE THREAD

**Issue by hyperloo** [HyperLoo/TaskManager-Server#1]
**How is the feature you adding to the App is related to the issue? Please describe.**
This Security will make the Server secure from the Javascript Injection to the server as well as DB.

**Describe the method/ package through which you have implemented the solution.**
Mention the details about the Package or the method you have used to overcome the issue.

And don't forget to ⭐ the repo!😁

**Comment by ryzbaka** [comment]
Done.
https://github.com/HyperLoo/TaskManager-Server/pull/5
