### ISSUE TITLE
Implement Form Validation at Backend Register

### ISSUE THREAD

**Issue by hyperloo** [HyperLoo/TaskManager-Server#2]
**How is the feature you adding to the App is related to the issue? Please describe.**
1) Name Field: *Required*, *No JS*
2) Password Field:  *Minimum Length: 8*, *Contains at least 1 special char, 1 number, 1 Capital Letter & 1 Small Letter*
3) Email Field: *Must be an Email*
And send the proper response code with the appropriate message.

**Describe the method/ package through which you have implemented the solution.**
Mention the details about the Package or the method you have used to overcome the issue.

**Comment by OmkarPh** [comment]
Hi @HyperLoo 
I would like to work on this !

**Comment by hyperloo** [comment]
> 
> 
> Hi @HyperLoo
> I would like to work on this !

Hey @OmkarPh 
Thanks for showing interest. If you need any help with the code, you can ask me. 

**Note:** Please add comments with the changes you made.

**Comment by OmkarPh** [comment]
Hi @HyperLoo, 
I plan to use Regex for validating password and email.
For name, I plan to keep a minimum limit of 3 characters for a name to be valid.

Is this OK, your suggestions on this are appreciated :)

**Comment by hyperloo** [comment]
Yes that's fine @OmkarPh and please try to test all the possible cases. 🙂

**Comment by OmkarPh** [comment]
Yes, I'll try my best

**Comment by hyperloo** [comment]
That's good! : )

**Comment by OmkarPh** [comment]
Hi there,
I completed everything inside the router for Register, but am wondering if i should add validation to login router too.
I don't think it is necessary to give constraints for login, we can simply authenticate and send if login is proper or not. However, I can add if you want.

What is your opinion brother, should I add in login or not?

**Comment by hyperloo** [comment]
Sure, that's fine.

**Comment by OmkarPh** [comment]
Hi @HyperLoo 
I am done with all necessary changes, you can see them in my forked repository.
However, I really want this contribution to be counted in hacktober fest, so can I make the PR on 1st of October

It would be great if you can wait :)

**Comment by hyperloo** [comment]
Alright, I will see the changes whenever you will make the PR. That will be fine from my side.

**Comment by OmkarPh** [comment]
Thanks bro 👍
